---
tags: [arduino, rasberry, IoT]
projects: [opendevice]
---
:toc:
:icons: font
:source-highlighter: prettify

== What is OpenDevice?

OpenDevice is a set of tools and APIs to build solutions for the *"Internet of Things"* like home automations systems, robotics, smart city, energy monitoring, security, sensor monitoring. +
Provide an open and unified framework to interconnect IoT devices, data, and applications over the Web,
if you need communication between software and hardware, probably your place is here.

The main objective is monitor and control inexpensive hardwares like Arduino, RaspberryPI and link:docs/#supported-devices[similar platforms], local(offline) or over the cloud using high-level programing languages and with abstraction of protocols and low-level details.

This allows you to focus on your project and innovation, leave obscure details of communication protocols and specifications with OpenDevice, you will make a major step towards the success of your project.

TIP: Plug your device (Arduino/Raspberypi/Other) to the Cloud and sync in real-time	

[source,java]
----
{"id":1,"content":"Hello, World!"}
----

See documentation at:
----
http://opendevice.criativasoft.com.br/
----
